version: 1.0.{build}
skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
    nodejs_version: "6.2.2" # This is the Choco version number
    COVERALLS_REPO_TOKEN:
       secure: umoRFggjKi3k6AUv84a9sxf/GYFsGm3weJh7zWLKfUTRnOJFlxN0KI5cntUhk2kV

cache:
  - packages ->  **\packages.config

branches:
  only:
    - master

services:
  - mongodb

# Add NodeJS/Gulp for the SASS compilation
install:
  - cd .\src\Syringe.Web\
  - npm install --global gulp-cli --loglevel=error
  - npm install --loglevel=error
  - gulp
  - cd ..\..\

# Update the assembly version numbers with the Appveyor version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Run grunt, and then the custom build script that runs Octopack
build_script:
    - ps: .\build\build.ps1

# Copy and convert all Octopack generated nupkg files into zip files
after_build:
  - ps: .\build\nupkg-to-zip.ps1
  - 7z a Syringe-%APPVEYOR_BUILD_VERSION%.zip .\build\_deploymentOutput\*.zip

# Generate test coverage and upload it to Coveralls.IO
after_test:
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Syringe*]*" -target:"packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" -targetargs:"/domain:single  src\Syringe.Tests\bin\release\Syringe.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

artifacts:
  - path: Syringe-$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersionZip

deploy:
- provider: GitHub
  auth_token:
    secure: 5sXorIkpeEIjJoM/zN1tQxST84WIM2Jkmd93H1UFiYNmO40C1RIuUgoUhYjCjcvi
  artifact: CurrentVersionZip
  draft: true
  force_update: false
  on:
    branch: master
